openapi: 3.0.1
info:
  title: oneOf test
  version: "1.0"
servers:
- url: http://localhost:8000/
paths:
  /state:
    get:
      operationId: getState
      responses:
        200:
          content:
            application/json:
              schema:
                discriminator:
                  mapping:
                    a-type: '#/components/schemas/ObjA'
                    b-type: '#/components/schemas/ObjB'
                  propertyName: realtype
                oneOf:
                - $ref: '#/components/schemas/ObjA'
                - $ref: '#/components/schemas/ObjB'
          description: OK
    post:
      operationId: createState
      requestBody:
        content:
          application/json:
            schema:
              discriminator:
                mapping:
                  a-type: '#/components/schemas/ObjA'
                  b-type: '#/components/schemas/ObjB'
                propertyName: realtype
              oneOf:
              - $ref: '#/components/schemas/ObjA'
              - $ref: '#/components/schemas/ObjB'
        required: true
      responses:
        201:
          description: OK
components:
  schemas:
    ObjA:
      properties:
        realtype:
          type: string
        message:
          type: string
      type: object
    ObjB:
      properties:
        realtype:
          type: string
        description:
          type: string
        code:
          format: int32
          type: integer
      type: object
