/*
 * oneOf test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package go_sample_api

type ObjB struct {
	Realtype string `json:"realtype,omitempty"`
	Description string `json:"description,omitempty"`
	Code int32 `json:"code,omitempty"`
}
