/*
 * oneOf test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package go_sample_api

type ObjA struct {
	Realtype string `json:"realtype,omitempty"`
	Message string `json:"message,omitempty"`
}
